### ISSUE TITLE
Find dataset.createby, dataset.modby => need to join Person table twice.  

### ISSUE THREAD

**Issue by liangd** [vkuznet/PyQueryBuilder#1]
There are there cases:
1.duplication in finds:
          find dataset.createby, dataset.modby
2.duplication in wheres:
          find dataset where dataset.createdby = A, dataset.modby =B
3.duplication cross finds and wheres:
          find dataset.createby where dataset.modby = C

This happens on attribute table only

**Comment by liangd** [comment]
1. different links via different table to Person table such as:
    find dataset.createby, run.createby.

**Comment by vkuznet** [comment]
The question is can you resolved algorithmically? If not, you can resolve it at presentation layer.

**Comment by liangd** [comment]
Hi Valentin,

This was solved by two patches, the solution is both algorithmically and presentation layer.
More information are remembered during parsing and mapping, to allowing figure out the correct sqlalchemy object.

patches:
1. applying alias on SQLAlchemy objects
2. fix the branch condition for no Froms during root_join.

**Comment by vkuznet** [comment]
Hi Dong,
thanks for update. I did see your updates, thanks to email notifications from github. But I must admit I hadn't finishing reading your QL paper draft. I'm sorry, but last several weeks were so crazy for me that I barely sleep. But don't worry I keep your paper in my backbag and I'll read it as soon as I can.
Valentin.
